version: '3'

services:
  mvcmovie:
    image: mvcmovie
    build:
      context: ./MvcMovie
      dockerfile: Dockerfile
    ports: 
      - "8000:80"
    depends_on:
      - db
  db:
    image: "microsoft/mssql-server-linux"
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "qwerty"
      ACCEPT_EULA: "Y"
      
